version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: craby_city
    ports:
      - 5432:5432
    volumes:
      - craby_vol:/var/lib/postgresql/data
    networks:
      - craby_net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 2023:2023
    environment:
      CITY_API_ADDR: 0.0.0.0
      CITY_API_PORT: 2023
      CITY_API_DB_USER: postgres
      CITY_API_DB_PASSWORD: postgres
      CITY_API_DB_URL: postgres:5432
    networks:
      - craby_net
  
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - craby_net
  
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    networks:
      - craby_net
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

volumes:
  craby_vol:

networks:
  craby_net:
    driver: bridge