apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crabycity-ingress
  namespace: craby-city
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    treafik.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: api.craby-city.bonnal.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crabycity-service
            port:
              number: 80
  tls:
  - hosts:
    - api.craby-city.bonnal.cloud
    secretName: crabycity-tls