apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name}}-deployment
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-deployment
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        env:
          - name: CITY_API_ADDR
            value: {{ .Values.cityApiAddr }}
          - name: CITY_API_PORT
            value: {{ .Values.cityApiPort | quote }} 
          - name: CITY_API_DB_URL
            value: {{ .Release.name}}-postgresql:5432
          - name: CITY_API_DB_USER
            value: {{ .Values.postgresUser }}
          - name: CITY_API_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: postgres-password