apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crabby-city
  namespace: argocd
spec:
  project: crabby-city-project
  source:
    repoURL: 'https://github.com/418-Error/craby_city'
    path: helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - tag.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crabbycrab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true