postgresql:
  auth:
    enablePostgresUser: true
    database: "craby_city"


postgresUser: "postgres"
cityApiAddr: "0.0.0.0"
cityApiPort: "80"

image:
  repository: "milou666/craby-city"

replicaCount: 1

service:
  internalPort: 80
  externalPort: 80