name: push

on:
    push:
        branches:
        - main
        - ci
        tags:
        - v*

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
          with:
            toolchain: nightly
            components: rustfmt
        - name: Run rustfmt
          run: cargo fmt --all -- --check
    clippy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
          with:
            toolchain: nightly
            components: clippy
        - name: Run clippy
          run : cargo clippy --all -- -D warnings
    push_to_registry:
        needs: [fmt, clippy]
        name: Push Docker image to Dockerhub
        runs-on: ubuntu-latest
        env:
            TAG: ${{ github.ref_name }}
        steps:
            - uses: actions/checkout@v4
            - name: Login to Dockerhub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ secrets.DOCKER_USERNAME }}/craby-city:${{ env.TAG }}
                    ${{ secrets.DOCKER_USERNAME }}/craby-city:latest
            