name: tests

on:
    pull_request:
        branches:
        - main

jobs:
    tests:
        services:
            # Label used to access the service container
            postgres:
              # Docker Hub image
              image: postgres
              # Provide the password for postgres
              env:
                POSTGRES_PASSWORD: postgres
              # Set health checks to wait until postgres has started
              options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
              ports:
                # Maps tcp port 5432 on service container to the host
                - 5432:5432
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
          with:
            toolchain: nightly
            components: rustfmt
        - name: Run tests
          run: DATABASE_URL=postgres://postgres:postgres@0.0.0.0:5432 cargo test